### ISSUE TITLE
Extract a 6.4.2 release to track new Sidekiq Release

### ISSUE THREAD

**Issue by bf4** [gemhome/sidekiq-delay_extensions#4]

**Comment by imajes** [comment]
thanks, i'll take a look at this!

**Comment by bf4** [comment]
then, after that, 6.5.0 etc

It'll be good to cut each since I accidentally released 6.4.1 before
6.4.0..

**Comment by bf4** [comment]
So much time has passed.  I'm just going to release the last 6.x gem
then we'll start are own 7.x where we can accept PRs since we'll fully own the code at that point.
